Script to get a post using Rest API to test it with the vDOM script.
luisherranz/block-hydration-experiments pull request #112
Opened 2022-11-30 13:25 UTC by c4rl0sbr4v0

I created an initial draft of a script that reads a CSV domains file, then, per domain it makes a request to the REST API in order to get the URL of the first post found and add it to another CSV.

I'm currently testing it and I'm having tons of 403 and sites with the REST API not enabled. Until I get a percentage to check if we should consider this approach, I will leave this PR as a draft.

There also some tasks pending or other possibilities:
  - [ ] Check if we can use RSS to get the link of the post instead of the REST API.
  - [ ] Use a DB to be able to stop and continue later with the script execution.

2022-11-30 13:48 UTC, SantosGuillamot commented
Thanks for opening this @c4rl0sbr4v0 !

Just to keep it in mind, some sites may have disabled access to the REST API and we will hit a "You are not allowed to access the REST API" (or something similar) message instead of the post.

2022-11-30 13:58 UTC, luisherranz commented on benchmark/getPostUris.mjs
> +				'/wp-json/wp/v2/posts?post_per_page=1'
Using `?rest_route=/wp/v2/posts&post_per_page=1` is a bit safer here.

2022-11-30 14:07 UTC, c4rl0sbr4v0 commented
> Just to keep it in mind, some sites may have disabled access to the REST API and we will hit a "You are not allowed to access the REST API" (or something similar) message instead of the post.

Yes! In that case, at the moment, we just skip it, catch and console. We can get the status and the response message if needed.

2022-11-30 14:24 UTC, SantosGuillamot commented
> Yes! In that case, at the moment, we just skip it, catch and console. We can get the status and the response message if needed. It's the first draft just to keep the record and an initial number of URLs.

Okay, great! 🙂 For reference, we could encounter at least two different messages:
* [REST API message](https://wpmoviesdemo.wpcomstaging.com/wp-json/wp/v2/templates): It returns a JSON saying it isn't allowed.
* [Warning page](https://wpcerber.com/wp-json/wp/v2/): It is a page saying you are not allowed.

2022-11-30 14:28 UTC, SantosGuillamot commented on benchmark/getPostUris.mjs
> +			baseURL: `https://${url}`,
Not sure about the implications, but [in the current script we are using `http` instead of `https`](https://github.com/WordPress/block-hydration-experiments/blob/perf-and-stress-testing/benchmark/index.mjs#L125). Maybe it is because if we use `https` in a site without a certificate, the browser returns an error, and the other way they are usually redirected?

2022-11-30 15:12 UTC, c4rl0sbr4v0 commented on benchmark/getPostUris.mjs
> +				'/wp-json/wp/v2/posts?post_per_page=1'
Done!

2022-11-30 17:01 UTC, c4rl0sbr4v0 commented on benchmark/getPostUris.mjs
> +		}
This is not needed, as appendFileSync creates the file if it does not exist.

2022-12-01 09:17 UTC, SantosGuillamot commented
I've just thought that we may want to skip Cloudflare sites if we don't want to get blocked. We could do something like [this](https://github.com/WordPress/block-hydration-experiments/blob/perf-and-stress-testing/benchmark/index.mjs#L88-L93), I guess.

2022-12-01 17:18 UTC, c4rl0sbr4v0 commented
I think is stable enough to be review ready. I'm getting about a 50% of posts using this script.

2022-12-02 08:15 UTC, SantosGuillamot commented
I was testing it, and it looks great so far. I am encountering many sites that are registering a post with many encoded characters in the url. Something like this: `/%d8%a3%d9%87%d9%84%d8%a7-%d8%a8%d8%a7%d9%84%d8%b9%d8%a7%d9%84%d9%85/`.

Is that expected? More than 50% of the urls I got are like that.

2022-12-02 08:30 UTC, SantosGuillamot requested changes
I've added some minor comments. Apart from that, it looks great to me 🙂 

I was wondering as well if it could make sense to try fetching the post through the REST API when the RSS fails. Basically because I think you already had that logic. But maybe it is not worthy. I leave it up to you 🙂

2022-12-02 08:30 UTC, SantosGuillamot commented on benchmark/getPostUris.mjs
> +	cloudfare: testCloudflare,
Small typo: It's `cloudflare` instead of `cloudfare`.

2022-12-02 08:30 UTC, SantosGuillamot commented on benchmark/getPostUris.mjs
> +	default: { concurrency: 10, database: 'posts_db', cloudfare: false },
Small typo: It's `cloudflare` instead of `cloudfare`.

2022-12-02 08:30 UTC, SantosGuillamot commented on benchmark/getPostUris.mjs
> +			console.log('Skip: Cloudfare site', url);
Small typo: It's `cloudflare` instead of `cloudfare`.

2022-12-02 08:30 UTC, SantosGuillamot commented on benchmark/getPostUris.mjs
> +				console.log('Skip: Cloudfare site', url);
Small typo: It's `cloudflare` instead of `cloudfare`.

2022-12-02 08:30 UTC, SantosGuillamot commented on benchmark/getPostUris.mjs
> +		'\nPlease provide a CSV file as an argument\n\nFor example: npm run benchmark 1.csv\n'
Just a small detail, but maybe we can change the error to say `npm run getposts` instead of `npm run benchmark`?

2022-12-02 09:37 UTC, c4rl0sbr4v0 commented on benchmark/getPostUris.mjs
> +	cloudfare: testCloudflare,
Copy-pasted, we need to update also the other file 😢

2022-12-02 09:49 UTC, c4rl0sbr4v0 commented
> I was wondering as well if it could make sense to try fetching the post through the REST API when the RSS fails.

We can do it, but also it will multiply the time of the script running by x1.8 more or less.  I don't know if it worths to be honest.

2022-12-02 10:17 UTC, c4rl0sbr4v0 commented
> I was testing it, and it looks great so far. I am encountering many sites that are registering a post with many encoded characters in the url. Something like this: /%d8%a3%d9%87%d9%84%d8%a7-%d8%a8%d8%a7%d9%84%d8%b9%d8%a7%d9%84%d9%85/.
Is that expected? More than 50% of the urls I got are like that.

Japanese and other special characters!!

zoes.tw/2021/10/23/1017%e6%a1%83%e5%9c%92amour%e8%ad%89%e5%a9%9a-%e5%87%b1%e9%88%9e%e6%9c%b1%e7%91%9c-%e5%a9%9a%e7%a6%ae%e9%8c%84%e5%bd%b1-%e7%b2%be%e8%8f%af%e7%89%88/ turns to be:
![Screenshot 2022-12-02 at 11 16 13](https://user-images.githubusercontent.com/37012961/205270063-2dc89c23-8b28-4e54-afd1-3c77d1634d13.jpg)

2022-12-02 10:20 UTC, SantosGuillamot approved these changes
LGTM! 🙂

2022-12-02 11:17 UTC, merged