Add `wp-show` directive attribute
luisherranz/block-hydration-experiments pull request #156
Opened 2023-02-20 16:25 UTC by SantosGuillamot

This pull request aims to replicate the behavior of the [`wp-show` directive tag (component)](https://github.com/WordPress/block-hydration-experiments/blob/main-wp-directives-plugin/src/runtime/components.js#L13-L22), but using a directive attribute instead.

It's true that in terms of functionality, the directive tag should be enough for now, but both approaches should be available. Especially if we end up [removing directive tags (components) from the proposal](https://github.com/WordPress/block-hydration-experiments/issues/152).

In [the movies demo](https://github.com/c4rl0sbr4v0/wp-movies-demo/), we will use this directive, so it would be great if we could just use directive tags.

2023-02-20 16:42 UTC, luisherranz requested changes
The code looks fine to me, but would you mind adding some e2e tests? Thanks!! 🙏

2023-02-21 11:05 UTC, SantosGuillamot commented
> The code looks fine to me, but would you mind adding some e2e tests? Thanks!! 🙏

Sure, I'll do that 🙂

2023-02-21 16:55 UTC, SantosGuillamot commented
I started adding some tests, but something is not working as expected. It seems the HTML generated is not correct, and I don't know why it seems to be passing the attributes to the next HTML tag. I'll review tomorrow in more detail why that is happening.

2023-02-22 12:46 UTC, SantosGuillamot commented
I've added more tests to check the toggling and that it works with context as well -> [Commit](https://github.com/WordPress/block-hydration-experiments/pull/156/commits/374e810f73163cf052400bf6f74c656d36690444).

In [this other commit](https://github.com/WordPress/block-hydration-experiments/pull/156/commits/04d142a46c9d525f172229d3653ecab60f6e2810), @luisherranz fixed the issue I mention [here](https://github.com/WordPress/block-hydration-experiments/pull/156#issuecomment-1438807273). However, we have to decide [What should be the HTML structure returned when wp-show is false?](https://github.com/WordPress/block-hydration-experiments/issues/159) before merging this PR. The current approach is working, but if we go with the other alternative, [the problem mentioned](https://github.com/WordPress/block-hydration-experiments/pull/156#issuecomment-1438807273) still persists.

2023-02-22 14:19 UTC, luisherranz commented
Let's merge this as it is and if we decide to go with the opposite approach, we'll change it.

I'll investigate the bug a bit and open another issue, as it's not related with this PR (it's a general bug).

2023-02-22 14:21 UTC, luisherranz approved these changes

2023-02-23 09:01 UTC, merged